server:
  port: 8082
  error:
    path: /error2

spring:
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: prepare-ion-project
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=prepareion
    username: sa
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
  security:
    user:
      name: tien
      password: 123